# Generated by Django 5.1.4 on 2024-12-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_question_designer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_designer',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question_designer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>'),
        ),
    ]
